import React, { useState } from 'react'

const rows = Array.from({ length: 10 }, (_, index) => ({
  id: `S25ADUS0743${String(index).padStart(2, '0')}`,
  risk: ['Risky', 'Risky', 'Alert', 'Normal', 'Normal', 'Risky', 'Normal', 'Normal', 'Alert', 'Normal'][index],
  total: [8, 6, 2, 3, 5, 1, 4, 2, 3, 6][index],
  date: ['15 Mar 2024 09:30', '22 Jun 2025 14:45', '08 Dec 2023 16:20', '03 Apr 2026 11:15', '18 Sep 2024 08:00', '29 Nov 2025 13:30', '14 Feb 2027 10:45', '07 Aug 2024 19:15', '25 Jan 2026 07:30', '12 May 2025 15:00'][index],
  atc: ['Overdue', 'Overdue', 'Soon Due', 'Overdue', 'Soon Due', 'Display value', 'Display value', 'Not Applicable', 'Not Applicable', 'Pending'][index],
}))
const fields = ['Shipment ID (comma separated)', 'House bill number (comma separated)', 'HBL Delivery Mode', 'Controlling Customer Code', 'Origin Country', 'Destination Country', 'Exception Owner Company', 'Exception Owner Branch']
const dateFilters = ['Created Date', 'ETD - First Leg', 'ETA - First Leg', 'ATD - First Leg', 'ATA - First Leg', 'Estimated Pickup', 'Actual Pickup', 'Estimated Delivery', 'Actual Delivery']
function Tag({ children, tone = 'neutral' }) { return <span className={`tag ${tone}`}>{children}</span> }
function Icon({ name, title }) { return <mc-icon icon={name} size="16" title={title} /> }
function Drawer({ title, children, onClose, className = '' }) { return <div className="overlay"><aside className={`drawer ${className}`}><div className="drawer-title"><h2>{title}</h2><button onClick={onClose} aria-label="Close"><Icon name="mi-times" title="Close" /></button></div>{children}</aside></div> }

export default function App() {
  const [filterOpen, setFilterOpen] = useState(false)
  const [columnOpen, setColumnOpen] = useState(false)
  const [selected, setSelected] = useState(null)
  const [search, setSearch] = useState('')
  const [threshold, setThreshold] = useState(24)
  const [unit, setUnit] = useState('Hour(s)')
  const [tooltip, setTooltip] = useState(false)
  const visibleRows = rows.filter((row) => row.id.toLowerCase().includes(search.toLowerCase()))
  return <>
    <header className="topbar"><button className="hamburger" aria-label="Open navigation"><Icon name="mi-bars-horizontal" title="Navigation" /></button><span className="brand-mark">✦</span><strong>Air One Platform</strong><span className="top-actions"><button aria-label="Search"><Icon name="mi-magnifying-glass" title="Search" /></button><button aria-label="Notifications"><Icon name="mi-bell" title="Notifications" /></button><button aria-label="Help"><Icon name="mi-question-circle" title="Help" /></button><button aria-label="User menu"><Icon name="mi-user-circle" title="User menu" /></button><button>CX⌄</button></span></header>
    <main className="page"><section className="page-head"><h1>Control Tower</h1><div><small>Control Tower Rule</small><strong>CSOP-V9.0, IOP-V9.0</strong><button className="quiet">Edit</button></div><button className="config">↗ Configuration Center</button></section>
      <nav className="tabs">{['Air Exceptions', 'Air Timeliness', 'Sea Exceptions', 'Document Exceptions', 'Reference Exceptions'].map((tab, index) => <button className={index === 0 ? 'active' : ''} key={tab}>{tab}</button>)}</nav>
      <section className="control-row"><div className="threshold"><span className="tooltip-anchor" onMouseEnter={() => setTooltip(true)} onMouseLeave={() => setTooltip(false)}>Set “Soon Due” Threshold Within <b><Icon name="mi-info-circle" title="Threshold information" /></b>{tooltip && <span className="tooltip">Shipments with missing or corrected system updates — milestone exceptions, air freight forwarding.</span>}</span><input type="number" min="0" step="1" value={threshold} onChange={(event) => setThreshold(Math.max(0, Math.trunc(Number(event.target.value) || 0)))} /><select value={unit} onChange={(event) => setUnit(event.target.value)}><option>Hour(s)</option><option>Day(s)</option></select><button className="primary">Apply</button></div><button className="filter-button" onClick={() => setFilterOpen(true)}><Icon name="mi-funnel" title="Filter" /> Filter (0)</button><button className="refresh"><Icon name="mi-arrow-clockwise" title="Refresh" /> Refresh</button></section>
      <section className="metrics">{[['Total Shipments', '180', 'Total active Air shipments in scope', ''], ['Shipments with Exceptions', '180', '330 Total open exceptions', 'mixed'], ['Shipments with Soon Due Exceptions', '180', '330 Total soon due exceptions', 'warning'], ['Shipments with Overdue Exceptions', '180', '330 Total overdue exceptions', 'error']].map(([title, value, caption, tone]) => <article key={title}><div>{title}<span className={`metric-dot ${tone}`} /></div><strong>{value}</strong> <small>Shipments</small><p>{caption}</p></article>)}</section>
      <section className="queue"><div className="queue-head"><h2>Exception Queue <sup>9</sup></h2><div><div className="search-field"><input aria-label="Search shipment" placeholder="Search Shipment ID / House Bill" value={search} onChange={(event) => setSearch(event.target.value)} /><Icon name="mi-magnifying-glass" title="Search" /></div><button onClick={() => setColumnOpen(true)}>Column View</button><button className="dark"><Icon name="mi-square-arrow-up-right" title="Export" /> Export Excel</button></div></div><div className="table-wrap"><table><thead><tr>{['Text', 'Shipment Risk', 'Total Exceptions', 'Export Milestone Overdue', 'Export Milestone Soon Due', 'Import Milestone Overdue', 'Import Milestone Soon Due', 'Date', 'ATC'].map((heading) => <th key={heading}>{heading}　<Icon name="mi-funnel" title="Filter column" /> <Icon name="mi-arrows-down-up" title="Sort column" /></th>)}</tr></thead><tbody>{visibleRows.map((row) => <tr key={row.id} onClick={() => setSelected(row)}><td><a href="#detail" onClick={(event) => event.preventDefault()}>{row.id}</a></td><td><Tag tone={row.risk === 'Risky' ? 'risk' : row.risk === 'Alert' ? 'alert' : 'normal'}>{row.risk}</Tag></td><td>{row.total}</td>{[1, 2, 3, 4].map((item) => <td key={item}><Tag tone={item % 2 ? 'overdue' : 'soon'}>ABC</Tag> <Tag tone={item % 2 ? 'overdue' : 'soon'}>ABC</Tag> <Tag tone={item % 2 ? 'overdue' : 'soon'}>ABC</Tag></td>)}<td>{row.date}</td><td><Tag tone={row.atc === 'Overdue' ? 'overdue' : row.atc === 'Soon Due' ? 'soon' : 'neutral'}>{row.atc}</Tag></td></tr>)}</tbody></table></div><div className="pagination"><span>Items per page: <select><option>10</option></select>　1–10 of 500 items</span><span><Icon name="mi-chevron-left" title="Previous page" />　 <b>1</b>　2　3　4　<Icon name="mi-chevron-right" title="Next page" /></span></div></section></main>
    {filterOpen && <Drawer title="Filter" onClose={() => setFilterOpen(false)} className="filter-drawer"><div className="drawer-actions"><button>Clear Filters</button><button className="dark" onClick={() => setFilterOpen(false)}>Apply Filters</button></div><h3>Shipment Identifiers</h3><div className="field-grid">{fields.map((field) => <label key={field}>{field}<input placeholder="Placeholder" /></label>)}</div><h3>Dates</h3><div className="date-grid">{dateFilters.map((field) => <label key={field}>{field}<div><input placeholder="YYYY-MM-DD" /><span>→</span><input placeholder="YYYY-MM-DD" /></div><small>□ Include Shipment with Missing Value</small></label>)}</div></Drawer>}
    {columnOpen && <Drawer title="Setup Column View" onClose={() => setColumnOpen(false)} className="column-drawer"><div className="column-group"><b>⊟　Category 1</b>{['Column name', 'Column name', 'Column name', 'Column name'].map((item, index) => <label key={index}><input type="checkbox" defaultChecked={index < 3} /> {item}</label>)}</div><div className="column-group"><b>⊟　Category 1</b>{['Column name', 'Column name', 'Column name', 'Column name'].map((item, index) => <label key={index}><input type="checkbox" defaultChecked={index < 3} /> {item}</label>)}</div><button className="reset" onClick={() => setColumnOpen(false)}>Reset to Default</button></Drawer>}
    {selected && <Drawer title={<><span>{selected.id}</span> <Tag tone="risk">{selected.risk}</Tag></>} onClose={() => setSelected(null)} className="detail-drawer"><h3>Shipment details</h3><div className="detail-grid">{[['Label', 'MH724932715'], ['Controlling customer', 'ROBBSOLGL – Robert Bosch'], ['Origin Destination', 'ORD → SIN'], ['HBL delivery mode', 'Value'], ['Service level', 'Value'], ['Export owner', 'Value'], ['Import owner', 'Value'], ['Created on', 'Value']].map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>{['Export Milestones', 'Import Milestones'].map((title) => <section className="milestones" key={title}><h3>{title}</h3><table><thead><tr><th>Code</th><th>Milestone</th><th>Actual Date</th><th>Due Date</th><th>Status</th></tr></thead><tbody>{['On Time', 'Soon Due', 'Overdue', 'Not Applicable', 'Pending'].map((status) => <tr key={status}><td>Text</td><td>Text</td><td>{selected.date}</td><td>{selected.date}</td><td><Tag tone={status === 'Overdue' ? 'overdue' : status === 'Soon Due' ? 'soon' : 'neutral'}>{status}</Tag></td></tr>)}</tbody></table></section>)}</Drawer>}
  </>
}
