import React, { useMemo, useState } from 'react'

const rows = [
  ['S25ADUS074301', 'Risky', 8, '15 Mar 2024 09:30', 'Overdue'], ['S25ADUS074302', 'Risky', 6, '22 Jun 2025 14:45', 'Overdue'],
  ['S25ADUS074303', 'Alert', 2, '08 Dec 2023 16:20', 'Soon Due'], ['S25ADUS074304', 'Normal', 3, '03 Apr 2026 11:15', 'Overdue'],
  ['S25ADUS074305', 'Normal', 5, '18 Sep 2024 08:00', 'Soon Due'], ['S25ADUS074306', 'Risky', 1, '29 Nov 2025 13:30', 'Pending'],
  ['S25ADUS074307', 'Normal', 4, '14 Feb 2027 10:45', 'Display value'], ['S25ADUS074308', 'Normal', 2, '07 Aug 2024 19:15', 'Not Applicable'],
  ['S25ADUS074309', 'Alert', 3, '25 Jan 2026 07:30', 'Not Applicable'], ['S25ADUS074310', 'Normal', 6, '12 May 2025 15:00', 'Pending'],
].map(([id, risk, total, date, atc]) => ({ id, risk, total, date, atc }))
const columns = ['Shipment ID', 'Shipment Risk', 'Total Exceptions', 'Export Milestone Overdue', 'Export Milestone Soon Due', 'Import Milestone Overdue', 'Import Milestone Soon Due', 'Date', 'ATC']
const fields = ['Shipment ID (comma separated)', 'House bill number (comma separated)', 'HBL Delivery Mode', 'Controlling Customer Code', 'Origin Country', 'Destination Country', 'Exception Owner Company', 'Exception Owner Branch']
const dates = ['Created Date', 'ETD - First Leg', 'ETA - First Leg', 'ATD - First Leg', 'ATA - First Leg', 'Estimated Pickup', 'Actual Pickup', 'Estimated Delivery', 'Actual Delivery']

const Icon = ({ name, title }) => <mc-icon icon={name.replace(/^mi-/, '')} size="16" title={title} />
const Tag = ({ children, tone = 'neutral' }) => <span className={`tag ${tone}`}>{children}</span>

function Drawer({ title, children, onClose, className = '' }) {
  return <div className="overlay" onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <aside className={`drawer ${className}`} role="dialog" aria-modal="true"><div className="drawer-title"><h2>{title}</h2><mc-button appearance="neutral" variant="plain" fit="small" icon="mi-times" label="Close" onClick={onClose} /></div>{children}</aside>
  </div>
}

export default function App() {
  const [drawer, setDrawer] = useState(null), [selected, setSelected] = useState(null), [search, setSearch] = useState('')
  const [threshold, setThreshold] = useState(24), [unit, setUnit] = useState('Hour(s)'), [tip, setTip] = useState(false), [sortAsc, setSortAsc] = useState(true)
  const [filterValues, setFilterValues] = useState({}), [visibleColumns, setVisibleColumns] = useState(columns)
  const filteredRows = useMemo(() => rows.filter((row) => row.id.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sortAsc ? a.id.localeCompare(b.id) : b.id.localeCompare(a.id)), [search, sortAsc])
  const filterCount = Object.values(filterValues).filter(Boolean).length
  const toggleColumn = (column) => setVisibleColumns((current) => current.includes(column) ? current.filter((item) => item !== column) : [...current, column])
  const openDetails = (row) => { setSelected(row); setDrawer('details') }

  return <>
    <header className="topbar"><button className="icon-button" aria-label="Open navigation"><Icon name="mi-bars-horizontal" title="Navigation" /></button><span className="brand-mark">✦</span><strong>Air One Platform</strong><span className="top-actions"><button aria-label="Search"><Icon name="mi-magnifying-glass" title="Search" /></button><button aria-label="Notifications"><Icon name="mi-bell" title="Notifications" /></button><button aria-label="Help"><Icon name="mi-question-circle" title="Help" /></button><button aria-label="User menu"><Icon name="mi-user-circle" title="User menu" /></button><button>CX⌄</button></span></header>
    <main className="page"><section className="page-head"><div><h1>Control Tower</h1><div className="rule"><small>Control Tower Rule</small><strong>CSOP-V9.0, IOP-V9.0</strong><mc-button appearance="neutral" variant="plain" fit="small" label="Edit" /></div></div><mc-button appearance="neutral" variant="plain" fit="small" icon="mi-square-arrow-up-right" label="Configuration Center" /></section>
      <nav className="tabs" aria-label="Control tower sections">{['Air Exceptions', 'Air Timeliness', 'Sea Exceptions', 'Document Exceptions', 'Reference Exceptions'].map((tab, index) => <button className={index === 0 ? 'active' : ''} key={tab}>{tab}</button>)}</nav>
      <section className="control-row"><div className="threshold"><span className="tooltip-anchor" onMouseEnter={() => setTip(true)} onMouseLeave={() => setTip(false)}>Set “Soon Due” Threshold Within <Icon name="mi-info-circle" title="Threshold information" />{tip && <span className="tooltip">Shipments with missing or corrected system updates — milestone exceptions, air freight forwarding.</span>}</span><mc-input type="number" fit="small" value={threshold} min="0" label="Threshold" hide-label onMcInput={(event) => setThreshold(Math.max(0, Number(event.target.value) || 0))} /><mc-select fit="small" value={unit} label="Unit" hide-label><mc-option value="Hour(s)">Hour(s)</mc-option><mc-option value="Day(s)">Day(s)</mc-option></mc-select><mc-button appearance="primary" fit="small" label="Apply" /></div><mc-button appearance="neutral" fit="small" icon="mi-funnel" label={`Filter (${filterCount})`} onClick={() => setDrawer('filter')} /><mc-button appearance="neutral" fit="small" icon="mi-arrow-clockwise" label="Refresh" /></section>
      <section className="metrics">{[['Total Shipments', '180', 'Total active Air shipments in scope', ''], ['Shipments with Exceptions', '180', '330 Total open exceptions', 'mixed'], ['Shipments with Soon Due Exceptions', '180', '330 Total soon due exceptions', 'warning'], ['Shipments with Overdue Exceptions', '180', '330 Total overdue exceptions', 'error']].map(([title, value, caption, tone]) => <article key={title}><div>{title}<span className={`metric-dot ${tone}`} /></div><strong>{value}</strong> <small>Shipments</small><p>{caption}</p></article>)}</section>
      <section className="queue"><div className="queue-head"><h2>Exception Queue <sup>{filteredRows.length}</sup></h2><div className="queue-actions"><div className="search-field"><mc-input fit="small" label="Search shipment" hide-label placeholder="Search Shipment ID / House Bill" value={search} onMcInput={(event) => setSearch(event.target.value)} /><Icon name="mi-magnifying-glass" title="Search" /></div><mc-button appearance="neutral" fit="small" label="Column View" onClick={() => setDrawer('columns')} /><mc-button appearance="secondary" fit="small" icon="mi-square-arrow-up-right" label="Export Excel" /></div></div><div className="table-wrap"><table><thead><tr>{columns.map((column) => visibleColumns.includes(column) && <th key={column}>{column}{column === 'Shipment ID' && <button className="table-icon" aria-label="Sort shipment ID" onClick={() => setSortAsc((current) => !current)}><Icon name="mi-arrows-down-up" title="Sort column" /></button>}</th>)}</tr></thead><tbody>{filteredRows.map((row) => <tr key={row.id} onClick={() => openDetails(row)}>{visibleColumns.includes('Shipment ID') && <td><a href="#detail" onClick={(event) => event.preventDefault()}>{row.id}</a></td>}{visibleColumns.includes('Shipment Risk') && <td><Tag tone={row.risk === 'Risky' ? 'risk' : row.risk === 'Alert' ? 'alert' : 'normal'}>{row.risk}</Tag></td>}{visibleColumns.includes('Total Exceptions') && <td>{row.total}</td>}{columns.slice(3, 7).map((column) => visibleColumns.includes(column) && <td key={column}><Tag tone={column.includes('Overdue') ? 'overdue' : 'soon'}>ABC</Tag> <Tag tone={column.includes('Overdue') ? 'overdue' : 'soon'}>ABC</Tag></td>)}{visibleColumns.includes('Date') && <td>{row.date}</td>}{visibleColumns.includes('ATC') && <td><Tag tone={row.atc === 'Overdue' ? 'overdue' : row.atc === 'Soon Due' ? 'soon' : 'neutral'}>{row.atc}</Tag></td>}</tr>)}</tbody></table></div><div className="pagination"><span>Items per page: <select aria-label="Items per page"><option>10</option></select>　1–{filteredRows.length} of 500 items</span><span><button aria-label="Previous page"><Icon name="mi-chevron-left" title="Previous page" /></button> <b>1</b>　2　3　4　<button aria-label="Next page"><Icon name="mi-chevron-right" title="Next page" /></button></span></div></section>
    </main>
    {drawer === 'filter' && <Drawer title="Filter" onClose={() => setDrawer(null)} className="filter-drawer"><div className="drawer-actions"><mc-button appearance="neutral" variant="plain" fit="small" label="Clear Filters" onClick={() => setFilterValues({})} /><mc-button appearance="primary" fit="small" label="Apply Filters" onClick={() => setDrawer(null)} /></div><h3>Shipment identifiers</h3><div className="field-grid">{fields.map((field) => <label key={field}>{field}<mc-input fit="small" label={field} hide-label placeholder="Placeholder" value={filterValues[field] || ''} onMcInput={(event) => setFilterValues({ ...filterValues, [field]: event.target.value })} /></label>)}</div><h3>Dates</h3><div className="date-grid">{dates.map((field) => <label key={field}>{field}<div><mc-input fit="small" label={`${field} from`} hide-label placeholder="YYYY-MM-DD" /><span>→</span><mc-input fit="small" label={`${field} to`} hide-label placeholder="YYYY-MM-DD" /></div><small><input type="checkbox" /> Include shipment with missing value</small></label>)}</div></Drawer>}
    {drawer === 'columns' && <Drawer title="Setup column view" onClose={() => setDrawer(null)} className="column-drawer"><div className="column-group"><b>⊟　Shipment details</b>{columns.slice(0, 5).map((column) => <label key={column}><input type="checkbox" checked={visibleColumns.includes(column)} onChange={() => toggleColumn(column)} /> {column}</label>)}</div><div className="column-group"><b>⊟　Milestone details</b>{columns.slice(5).map((column) => <label key={column}><input type="checkbox" checked={visibleColumns.includes(column)} onChange={() => toggleColumn(column)} /> {column}</label>)}</div><mc-button appearance="neutral" variant="plain" fit="small" label="Reset to Default" onClick={() => setVisibleColumns(columns)} /></Drawer>}
    {drawer === 'details' && selected && <Drawer title={<><span>{selected.id}</span> <Tag tone="risk">{selected.risk}</Tag></>} onClose={() => { setDrawer(null); setSelected(null) }} className="detail-drawer"><h3>Shipment details</h3><div className="detail-grid">{[['Label', 'MH724932715'], ['Controlling customer', 'ROBBSOLGL – Robert Bosch'], ['Origin destination', 'ORD → SIN'], ['HBL delivery mode', 'Value'], ['Service level', 'Value'], ['Export owner', 'Value'], ['Import owner', 'Value'], ['Created on', 'Value']].map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>{['Export milestones', 'Import milestones'].map((title) => <section className="milestones" key={title}><h3>{title}</h3><table><thead><tr><th>Code</th><th>Milestone</th><th>Actual date</th><th>Due date</th><th>Status</th></tr></thead><tbody>{['On Time', 'Soon Due', 'Overdue', 'Not Applicable', 'Pending'].map((status) => <tr key={status}><td>Text</td><td>Text</td><td>{selected.date}</td><td>{selected.date}</td><td><Tag tone={status === 'Overdue' ? 'overdue' : status === 'Soon Due' ? 'soon' : 'neutral'}>{status}</Tag></td></tr>)}</tbody></table></section>)}</Drawer>}
  </>
}
